/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.journaliste.Interfaces;

import fr.miage.toulouse.journaliste.Entity.Article;
import fr.miage.toulouse.journaliste.Entity.Constants;
import fr.miage.toulouse.journaliste.Entity.JMSProvider;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author trongvo
 */
public class JournalisteMain extends javax.swing.JFrame {
    private static final long serialVersionUID = 1913625705010153425L;
    JMSProvider sender;

    // les arttributs d'un article
    private String nameArticle;
    private String codeArticle;
    private String nameAuthor;
    private List<String> keywords;
    private String content;
//        private String codeTitre;
//        private String nameTitre;

    private String messError;
    private static FocusListener textNomArticleFocusListener;
//        private static FocusListener textCodeTitreFocusListener;
    /**
     * Creates new form JournalisteMain
     */
    public JournalisteMain() {
        initComponents();
        this.sender = new JMSProvider();
        textNomArticleFocusListener = new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) { }

            @Override
            public void focusLost(FocusEvent e) {
                nameArticle = textFieldNomArticle.getText();
                String[] arrayNomArticle = nameArticle.split(" ");
                codeArticle="";
                for(String name : arrayNomArticle){
                    codeArticle += Character.toUpperCase(name.charAt(0));
                }
                textFieldCodeArticle.setText(codeArticle);
            }
        };
//        textCodeTitreFocusListener = new FocusListener() {
//            @Override
//            public void focusGained(FocusEvent e) {
//            }
//
//            @Override
//            public void focusLost(FocusEvent e) {
//                nameTitre = textFieldNomTitre.getText();
//                String[] arrayNomTitre = nameTitre.split(" ");
//                codeTitre="";
//                for(String name : arrayNomTitre){
//                    codeTitre += Character.toUpperCase(name.charAt(0));
//                }
//                textFieldCodeTitre.setText(codeTitre);
//            }
//        };
        this.textFieldNomArticle.addFocusListener(textNomArticleFocusListener);
       // this.textFieldNomTitre.addFocusListener(textCodeTitreFocusListener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAuteur = new javax.swing.JLabel();
        jLabelNomArticle = new javax.swing.JLabel();
        textFieldAuteur = new javax.swing.JTextField();
        textFieldNomArticle = new javax.swing.JTextField();
        jLabelNomArticle1 = new javax.swing.JLabel();
        textFieldCodeArticle = new javax.swing.JTextField();
        jLabelNomkeywords = new javax.swing.JLabel();
        textFieldKeywords = new javax.swing.JTextField();
        jLabelNomkeywords1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaContent = new javax.swing.JTextArea();
        buttonEnvoyerArticle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Journaliste"));

        jLabelAuteur.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelAuteur.setText("Auteur");
        jLabelAuteur.setToolTipText("");

        jLabelNomArticle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelNomArticle.setText("Nom Article");
        jLabelNomArticle.setToolTipText("");

        textFieldAuteur.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        textFieldNomArticle.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        textFieldNomArticle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldNomArticleFocusLost(evt);
            }
        });

        jLabelNomArticle1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelNomArticle1.setText("Code Article");
        jLabelNomArticle1.setToolTipText("");

        textFieldCodeArticle.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jLabelNomkeywords.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelNomkeywords.setText("Mots Clés");
        jLabelNomkeywords.setToolTipText("");

        textFieldKeywords.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        textFieldKeywords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldKeywordsActionPerformed(evt);
            }
        });

        jLabelNomkeywords1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelNomkeywords1.setText("Contenu");
        jLabelNomkeywords1.setToolTipText("");

        textAreaContent.setColumns(20);
        textAreaContent.setRows(5);
        jScrollPane1.setViewportView(textAreaContent);

        buttonEnvoyerArticle.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        buttonEnvoyerArticle.setText("Envoyer");
        buttonEnvoyerArticle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonEnvoyerArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnvoyerArticleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 99, 100));
        jLabel1.setText("(séparé par \";\")");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonEnvoyerArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNomkeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(textFieldKeywords))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNomArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(textFieldNomArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelNomArticle1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(textFieldCodeArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomkeywords1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(textFieldAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabelNomArticle1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCodeArticle)
                    .addComponent(jLabelNomArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNomArticle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomkeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldKeywords))
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelNomkeywords1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonEnvoyerArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldKeywordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldKeywordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldKeywordsActionPerformed

    private void buttonEnvoyerArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnvoyerArticleActionPerformed
        if(checkValidation()){
            this.nameArticle = textFieldNomArticle.getText();
            this.codeArticle = textFieldCodeArticle.getText();
            this.content = textAreaContent.getText();
            this.nameAuthor = textFieldAuteur.getText();
            this.keywords = Arrays.asList(textFieldKeywords.getText().split(";"));
            //this.codeTitre = textFieldCodeTitre.getText();

            Article article = new Article(nameArticle, codeArticle, nameAuthor, keywords, content);
            JOptionPane.showMessageDialog(this, "Article envoyé avec succuès!");
            sender.sendArticle(article);
            textFieldNomArticle.setText("");
            textFieldCodeArticle.setText("");
            textAreaContent.setText("");
            textFieldAuteur.setText("");
            textFieldKeywords.setText("");
//            textFieldNomTitre.setText("");
//            textFieldCodeTitre.setText("");         
        }else{
            JOptionPane.showMessageDialog(this, messError, "Inane warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_buttonEnvoyerArticleActionPerformed

    private void textFieldNomArticleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNomArticleFocusLost
//        this.nameArticle = textFieldNomArticle.getText();
//        String[] arrayNomArticle = this.nameArticle.split(" ");
//        for(String name : arrayNomArticle){
//            this.codeArticle += name.charAt(0);
//        }
    }//GEN-LAST:event_textFieldNomArticleFocusLost

    private boolean checkValidation(){
        if(textFieldAuteur.getText().equals("")){
            messError = Constants.EMPTY_NAME_AUTHOR;
            return false;
        }
        
        if(textFieldNomArticle.getText().equals("")){
            messError = Constants.EMPTY_NAME_ARTICLE;
            return false;
        }
        
        if(textFieldKeywords.getText().equals("")){
            messError = Constants.EMPTY_KEYWORDS;
            return false;
        }
        
        if(textAreaContent.getText().equals("")){
            messError = Constants.EMPTY_CONTENT_ARTICLE;
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JournalisteMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JournalisteMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JournalisteMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JournalisteMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JournalisteMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnvoyerArticle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAuteur;
    private javax.swing.JLabel jLabelNomArticle;
    private javax.swing.JLabel jLabelNomArticle1;
    private javax.swing.JLabel jLabelNomkeywords;
    private javax.swing.JLabel jLabelNomkeywords1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaContent;
    private javax.swing.JTextField textFieldAuteur;
    private javax.swing.JTextField textFieldCodeArticle;
    private javax.swing.JTextField textFieldKeywords;
    private javax.swing.JTextField textFieldNomArticle;
    // End of variables declaration//GEN-END:variables
}
