/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.interfaces;

import fr.miage.toulouse.misesouspresse.MiseSousPresse;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trongvo
 */
public class MiseSousPressMain extends javax.swing.JFrame {
    
    private final String[] tableArticleReceivedHeaders = {"Choisir", "Theme","Nom Artcile", "Code Article", "Auteur", "Contenu", "Date Création"};
    private final String[] tablePubliciteReceivedHeaders = {"Choisir", "Nom", "Description"};
    
    private DefaultTableModel tableArticlesModel;
    private DefaultTableModel tablePubsModel;
    
    private MiseSousPresse miseSousPresse;
    /**
     * Creates new form MiseSousPressMain
     */
    public MiseSousPressMain() {
        initComponents();
        miseSousPresse = new MiseSousPresse();
        miseSousPresse.start();
        tableArticlesModel = new DefaultTableModel(){
        @Override
        public Class getColumnClass(int columnIndex) {
           return columnIndex == 0 ? Boolean.class : super.getColumnClass(columnIndex);
        }};
        tablePubsModel = new DefaultTableModel(){
        @Override
        public Class getColumnClass(int columnIndex) {
           return columnIndex == 0 ? Boolean.class : super.getColumnClass(columnIndex);
        }};
        
        tableArticlesModel.setColumnIdentifiers(tableArticleReceivedHeaders);
        tablePubsModel.setColumnIdentifiers(tablePubliciteReceivedHeaders);
        tableArticles.setModel(tableArticlesModel);
        tablePubs.setModel(tablePubsModel);
        setTablesSize();
    }

    public void setTablesSize(){
        tableArticles.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tableArticles.getColumnModel().getColumn(0).setPreferredWidth(90);
        tableArticles.getColumnModel().getColumn(1).setPreferredWidth(120);
        tableArticles.getColumnModel().getColumn(2).setPreferredWidth(120);
        tableArticles.getColumnModel().getColumn(3).setPreferredWidth(90);
        tableArticles.getColumnModel().getColumn(4).setPreferredWidth(160);
        tableArticles.getColumnModel().getColumn(5).setPreferredWidth(350);
        tableArticles.getColumnModel().getColumn(6).setPreferredWidth(160);
        
        tablePubs.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablePubs.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablePubs.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablePubs.getColumnModel().getColumn(2).setPreferredWidth(790);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        tabGetArticlesPubs = new javax.swing.JPanel();
        buttonGetArticles = new javax.swing.JButton();
        jLabelArticlesReceived = new javax.swing.JLabel();
        jLabelPubsReceived1 = new javax.swing.JLabel();
        jTextNbrArticles = new javax.swing.JTextField();
        jTextNbrPubs = new javax.swing.JTextField();
        tabCreateVolume = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePubs = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableArticles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1090, 693));

        tabGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mise Sous Presse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(36, 228, 100))); // NOI18N

        tabGetArticlesPubs.setPreferredSize(new java.awt.Dimension(1090, 637));

        buttonGetArticles.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        buttonGetArticles.setText("Recuperer Les ARTICLES");
        buttonGetArticles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGetArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetArticlesActionPerformed(evt);
            }
        });

        jLabelArticlesReceived.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelArticlesReceived.setText("Nombre d'ARTICLES récupérés : ");

        jLabelPubsReceived1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelPubsReceived1.setText("Nombre de PUBLICITES récupérées : ");

        javax.swing.GroupLayout tabGetArticlesPubsLayout = new javax.swing.GroupLayout(tabGetArticlesPubs);
        tabGetArticlesPubs.setLayout(tabGetArticlesPubsLayout);
        tabGetArticlesPubsLayout.setHorizontalGroup(
            tabGetArticlesPubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGetArticlesPubsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabGetArticlesPubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGetArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabGetArticlesPubsLayout.createSequentialGroup()
                        .addGroup(tabGetArticlesPubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelArticlesReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPubsReceived1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(tabGetArticlesPubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNbrPubs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNbrArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(746, Short.MAX_VALUE))
        );
        tabGetArticlesPubsLayout.setVerticalGroup(
            tabGetArticlesPubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGetArticlesPubsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(buttonGetArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(tabGetArticlesPubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArticlesReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNbrArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(tabGetArticlesPubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPubsReceived1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNbrPubs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(329, 329, 329))
        );

        tabGeneral.addTab("Recuperer les Articles et les Publicités", tabGetArticlesPubs);

        tabCreateVolume.setPreferredSize(new java.awt.Dimension(1090, 637));

        tablePubs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablePubs);

        tableArticles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableArticles);

        javax.swing.GroupLayout tabCreateVolumeLayout = new javax.swing.GroupLayout(tabCreateVolume);
        tabCreateVolume.setLayout(tabCreateVolumeLayout);
        tabCreateVolumeLayout.setHorizontalGroup(
            tabCreateVolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCreateVolumeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCreateVolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        tabCreateVolumeLayout.setVerticalGroup(
            tabCreateVolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCreateVolumeLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        tabGeneral.addTab("Creer un Volume", tabCreateVolume);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral)
        );

        tabGeneral.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGetArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetArticlesActionPerformed
        
        jTextNbrArticles.setText(String.valueOf(miseSousPresse.getNbrArticles()));
        jTextNbrPubs.setText(String.valueOf(miseSousPresse.getListPublicites().size()));
    }//GEN-LAST:event_buttonGetArticlesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiseSousPressMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiseSousPressMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiseSousPressMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiseSousPressMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiseSousPressMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGetArticles;
    private javax.swing.JLabel jLabelArticlesReceived;
    private javax.swing.JLabel jLabelPubsReceived1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextNbrArticles;
    private javax.swing.JTextField jTextNbrPubs;
    private javax.swing.JPanel tabCreateVolume;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JPanel tabGetArticlesPubs;
    private javax.swing.JTable tableArticles;
    private javax.swing.JTable tablePubs;
    // End of variables declaration//GEN-END:variables
}
